remove \n

diff --git a/.github/workflows/snap.yaml b/.github/workflows/snap.yaml
--- a/.github/workflows/snap.yaml
+++ b/.github/workflows/snap.yaml
@@ -17,35 +17,35 @@ jobs:
       branch-name: main
       snap-name: ros2-talker-listener
       test-script: |
-                    #!/bin/bash\n
-                    sudo snap install ros2-cli --channel=foxy/beta\n
-                    wait\n
+                    #!/bin/bash
+                    sudo snap install ros2-cli --channel=foxy/beta
+                    wait
 
-                    check_node() {\n
-                        local node_name=$1\n
-                        ros2-cli.ros2 node list | grep -q "/$node_name"\n
-                        if [ $? -eq 0 ]; then\n
-                            echo "$node_name is running."\n
-                        else\n
-                            echo "Error - $node_name is not running."\n
-                            exit 1\n
-                        fi\n
-                    }\n
-                    check_topic() {\n
-                        local topic_name=$1\n
-                        local pub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Publisher count:" | awk '{print $3}')\n
-                        local sub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Subscription count:" | awk '{print $3}')\n
-                        if [ "$pub_count" -gt 0 ] && [ "$sub_count" -gt 0 ]; then\n
-                            echo "$topic_name has publishers and subscribers."\n
-                        else\n
-                            echo "Error - $topic_name has no publishers or subscribers."\n
-                            exit 1\n
-                        fi\n
-                    }\n
+                    check_node() {
+                        local node_name=$1
+                        ros2-cli.ros2 node list | grep -q "/$node_name"
+                        if [ $? -eq 0 ]; then
+                            echo "$node_name is running."
+                        else
+                            echo "Error - $node_name is not running."
+                            exit 1
+                        fi
+                    }
+                    check_topic() {
+                        local topic_name=$1
+                        local pub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Publisher count:" | awk '{print $3}')
+                        local sub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Subscription count:" | awk '{print $3}')
+                        if [ "$pub_count" -gt 0 ] && [ "$sub_count" -gt 0 ]; then
+                            echo "$topic_name has publishers and subscribers."
+                        else
+                            echo "Error - $topic_name has no publishers or subscribers."
+                            exit 1
+                        fi
+                    }
 
-                    timeout 10s ros2-talker-listener &
+                    timeout 3s ros2-talker-listener &
                     check_node listener &
                     check_node talker &
-                    check_topic chatter\n
-                    wait\n
-                    echo "All checks passed successfully."\n
+                    check_topic chatter
+                    wait
+                    echo "All checks passed successfully."
